---
# file: roles/haproxy/tasks/config.yml

- name: "Verify ssl certificate existence"
  stat:
    path: "{{ haproxy_ssl_certificate }}"
  register: stat_ssl_crt
  tags: [ haproxy-certbot ]

- block:
  - name: "Install ssl-cert package"
    apt:
      name: ssl-cert
    when: ansible_os_family == 'Debian'
    tags: [ haproxy-certbot ]

  - name: "Generate snakeoil certificate"
    shell: /usr/sbin/make-ssl-cert generate-default-snakeoil
    args:
      creates: /etc/ssl/certs/ssl-cert-snakeoil.pem
    tags: [ haproxy-certbot, skip_ansible_lint ]

  - name: "Create PEM directory"
    file:
      path: /etc/ssl/pem
      state: directory
      mode: 0755
    tags: [ haproxy-certbot ]

  - name: "Generate a PEM file from .key and .crt for snakeoil"
    shell: cat /etc/ssl/certs/ssl-cert-snakeoil.pem /etc/ssl/private/ssl-cert-snakeoil.key > /etc/ssl/pem/ssl-cert-snakeoil.pem
    args:
      creates: /etc/ssl/pem/ssl-cert-snakeoil.pem
    tags: [ haproxy-certbot ]

  - name: "Correct missing SSL Zertificate and use Snakeoil"
    set_fact:
      haproxy_ssl_certificate: "/etc/ssl/pem/ssl-cert-snakeoil.pem"
    tags: [ haproxy-certbot ]

  when: not stat_ssl_crt.stat.exists

- name: "Download DH4096 file"
  get_url:
    dest: /etc/ssl/dh4096.pem
    url: "https://ssl-config.mozilla.org/ffdhe4096.txt"
    checksum: "sha256:64852d6890ff9e62eecd1ee89c72af9af244dfef5b853bcedea3dfd7aade22b3"
    owner: root
    group: root
    mode: 0644
  when: haproxy_ssl_generate_dh4096
  tags: [ haproxy-certbot ]

- name: Copying the OCSP updater
  copy:
    src: haproxy-ocsp-fetch
    dest: /usr/local/bin/haproxy-ocsp-fetch
    owner: root
    group: root
    mode: 0755
  notify: fetch OCSP stapling info
  tags: [ haproxy-certbot, haproxy-install ]

- name: Setting up a cron job email address
  cron:
    cron_file: haproxy-ocsp-fetch
    env: true
    name: MAILTO
    user: root
    job: "{{ haproxy_ocsp_cron_email | default('root') }}"
  tags: [ haproxy-certbot, haproxy-install ]

- name: Setting up a cron job for OCSP fetchig
  cron:
    cron_file: haproxy-ocsp-fetch
    user: root
    name: haproxy-ocsp-fetch
    minute: "{{ 60 | random(seed=inventory_hostname) }}"
    hour: "{{ 24 | random(seed=inventory_hostname) }}"
    job: /usr/local/bin/haproxy-ocsp-fetch
  tags: [ haproxy-certbot, haproxy-install ]

- name: Configuring HAproxy
  template:
    src: etc/haproxy/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    validate: 'haproxy -f %s -c'
  notify: reload haproxy
  ignore_errors: True

