---
# file: roles/haproxy/tasks/main.yml
- name: Include OS variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - haproxy
    - haproxy-install
    - haproxy-firewall
    - haproxy-selinux
    - haproxy-config
    - haproxy-sysctl
    - haproxy-letsencrypt

- include: install.yml
  tags: [ haproxy, haproxy-install ]

- include: firewall.yml
  tags: [ haproxy, haproxy-firewall ]
  when: haproxy_firewalld | bool

- include: selinux.yml
  tags: [ haproxy, haproxy-selinux ]
  when: haproxy_selinux | bool

- include: config.yml
  tags: [ haproxy, haproxy-config ]

- include: sysctl.yml
  tags: [ haproxy, haproxy-sysctl ]

- include: letsencrypt.yml
  tags: [ haproxy ]
  when: haproxy_letsencrypt is defined and haproxy_letsencrypt

